In [2]:
import pandas as pd
from dask import dataframe as dd
import numpy as np
import databricks.koalas as ks
from pyspark.sql import SparkSession

In [138]:
npidata_raw = dd.read_csv('data/npidata_pfile_20050523-20210207.csv',low_memory =False,
                         dtype={'Healthcare Provider Primary Taxonomy Switch_11': 'object',
       'NPI': 'object','Entity Type Code' :'object',
        'Healthcare Provider Primary Taxonomy Switch_12': 'object',
       'Healthcare Provider Primary Taxonomy Switch_13': 'object',
       'Healthcare Provider Primary Taxonomy Switch_14': 'object',
       'Healthcare Provider Primary Taxonomy Switch_15': 'object',
       'Healthcare Provider Taxonomy Code_11': 'object',
       'Healthcare Provider Taxonomy Code_12': 'object',
       'Healthcare Provider Taxonomy Code_13': 'object',
       'Healthcare Provider Taxonomy Code_14': 'object',
       'Healthcare Provider Taxonomy Code_15': 'object',
       'Healthcare Provider Taxonomy Group_11': 'object',
       'Healthcare Provider Taxonomy Group_12': 'object',
       'Healthcare Provider Taxonomy Group_13': 'object',
       'Healthcare Provider Taxonomy Group_14': 'object',
       'Healthcare Provider Taxonomy Group_15': 'object',
       'Other Provider Identifier Issuer_16': 'object',
       'Other Provider Identifier Issuer_17': 'object',
       'Other Provider Identifier Issuer_18': 'object',
       'Other Provider Identifier Issuer_19': 'object',
       'Other Provider Identifier Issuer_20': 'object',
       'Other Provider Identifier Issuer_21': 'object',
       'Other Provider Identifier Issuer_22': 'object',
       'Other Provider Identifier Issuer_23': 'object',
       'Other Provider Identifier Issuer_24': 'object',
       'Other Provider Identifier Issuer_25': 'object',
       'Other Provider Identifier Issuer_26': 'object',
       'Other Provider Identifier Issuer_27': 'object',
       'Other Provider Identifier Issuer_28': 'object',
       'Other Provider Identifier Issuer_29': 'object',
        'Other Provider Identifier_31':'object',
'Other Provider Identifier_32': 'object', 
'Other Provider Identifier_33': 'object', 'Other Provider Identifier_38':'object',
       'Other Provider Identifier State_16': 'object',
       'Other Provider Identifier State_17': 'object',
       'Other Provider Identifier State_18': 'object',
       'Other Provider Identifier State_19': 'object',
       'Other Provider Identifier State_20': 'object',
       'Other Provider Identifier State_21': 'object',
       'Other Provider Identifier State_22': 'object',
       'Other Provider Identifier State_23': 'object',
       'Other Provider Identifier State_24': 'object',
       'Other Provider Identifier State_25': 'object',
       'Other Provider Identifier State_26': 'object',
       'Other Provider Identifier State_27': 'object',
       'Other Provider Identifier State_28': 'object',
       'Other Provider Identifier State_29': 'object',
       'Other Provider Identifier State_30': 'object',
       'Other Provider Identifier State_31': 'object',
       'Other Provider Identifier State_32': 'object',
       'Other Provider Identifier State_33': 'object',
       'Other Provider Identifier State_34': 'object',
       'Other Provider Identifier State_35': 'object',
       'Other Provider Identifier State_36': 'object',
       'Other Provider Identifier State_37': 'object',
       'Other Provider Identifier State_38': 'object',
       'Other Provider Identifier State_39': 'object',
       'Other Provider Identifier State_40': 'object',
       'Other Provider Identifier State_41': 'object',
       'Other Provider Identifier State_42': 'object',
       'Other Provider Identifier State_43': 'object',
       'Other Provider Identifier State_44': 'object',
       'Other Provider Identifier State_45': 'object',
       'Other Provider Identifier State_46': 'object',
       'Other Provider Identifier State_47': 'object',
       'Other Provider Identifier_10': 'object',
       'Other Provider Identifier_13': 'object',
       'Other Provider Identifier_14': 'object',
       'Other Provider Identifier_15': 'object',
       'Other Provider Identifier_16': 'object',
       'Other Provider Identifier_17': 'object',
       'Other Provider Identifier_18': 'object',
       'Other Provider Identifier_19': 'object',
       'Other Provider Identifier_20': 'object',
       'Other Provider Identifier_21': 'object',
       'Other Provider Identifier_22': 'object',
       'Other Provider Identifier_23': 'object',
       'Other Provider Identifier_24': 'object',
       'Other Provider Identifier_25': 'object',
       'Other Provider Identifier_26': 'object',
       'Other Provider Identifier_27': 'object',
       'Other Provider Identifier_28': 'object',
       'Other Provider Identifier_29': 'object',
       'Other Provider Identifier_30': 'object',
       'Other Provider Identifier_34': 'object',
       'Other Provider Identifier_35': 'object',
       'Other Provider Identifier_36': 'object',
       'Other Provider Identifier_39': 'object',
       'Other Provider Identifier_40': 'object',
       'Other Provider Identifier_44': 'object',
       'Other Provider Identifier_45': 'object',
       'Provider Business Mailing Address Postal Code': 'object',
       'Provider Business Practice Location Address Telephone Number': 'object',
       'Provider Business Practice Location Address Postal Code': 'object',
       'Provider License Number State Code_11': 'object',
       'Provider License Number State Code_12': 'object',
       'Provider License Number State Code_13': 'object',
       'Provider License Number State Code_14': 'object',
       'Provider License Number State Code_15': 'object',
       'Provider License Number State Code_6': 'object',
       'Provider License Number State Code_8': 'object',
       'Provider License Number_11': 'object',
       'Provider License Number_12': 'object',
       'Provider License Number_13': 'object',
       'Provider License Number_14': 'object',
       'Provider License Number_15': 'object',
       'Provider License Number_5': 'object',
       'Provider License Number_6': 'object',
       'Provider License Number_8': 'object',
       'Provider Other Name Suffix Text': 'object',
                               'Authorized Official Telephone Number': 'object',
       'Other Provider Identifier Issuer_30': 'object',
       'Other Provider Identifier Issuer_31': 'object',
       'Other Provider Identifier Issuer_32': 'object',
       'Other Provider Identifier Issuer_33': 'object',
       'Other Provider Identifier Issuer_34': 'object',
       'Other Provider Identifier Issuer_35': 'object',
       'Other Provider Identifier Issuer_36': 'object',
       'Other Provider Identifier Issuer_41': 'object',
       'Other Provider Identifier State_48': 'object',
       'Other Provider Identifier_41': 'object',
       'Other Provider Identifier_47': 'object',
       'Other Provider Identifier_48': 'object',
       'Provider Business Mailing Address Fax Number': 'object',
       'Provider Business Practice Location Address Fax Number': 'object',
                               'Other Provider Identifier Issuer_37': 'object',
       'Other Provider Identifier Issuer_38': 'object',
       'Other Provider Identifier Issuer_39': 'object',
       'Other Provider Identifier Issuer_40': 'object',
            'Other Provider Identifier Issuer_42': 'object',
       'Other Provider Identifier Issuer_43': 'object',
       'Other Provider Identifier Issuer_44': 'object',
       'Other Provider Identifier Issuer_45': 'object',
       'Other Provider Identifier Issuer_46': 'object',
       'Other Provider Identifier Issuer_47': 'object',
       'Other Provider Identifier Issuer_48': 'object',
       'Other Provider Identifier Issuer_49': 'object',
       'Other Provider Identifier_49': 'object','Other Provider Identifier_42': 'object',
        'Other Provider Identifier_37': 'object',
       'Other Provider Identifier_43': 'object',
       'Other Provider Identifier_46': 'object',
    'Other Provider Identifier Issuer_50': 'object',
       'Other Provider Identifier State_49': 'object',
       'Other Provider Identifier State_50': 'object',
                                'Other Provider Identifier_50': 'object'
                               }
                         )

In [140]:
npidata  = npidata_raw[['NPI','Entity Type Code','Provider Organization Name (Legal Business Name)',
                               'Provider Last Name (Legal Name)','Provider First Name',
            'Provider Middle Name','Provider Name Prefix Text','Provider Name Suffix Text',
                'Provider Credential Text','Provider First Line Business Mailing Address',
                'Provider Second Line Business Mailing Address','Provider Business Mailing Address City Name',
         'Provider Business Mailing Address State Name','Provider Business Mailing Address Postal Code']]

In [141]:
npi_tax_switch= npidata_raw[['NPI',
    'Healthcare Provider Primary Taxonomy Switch_1','Healthcare Provider Primary Taxonomy Switch_2',
    'Healthcare Provider Primary Taxonomy Switch_3','Healthcare Provider Primary Taxonomy Switch_4',
    'Healthcare Provider Primary Taxonomy Switch_5','Healthcare Provider Primary Taxonomy Switch_6',
    'Healthcare Provider Primary Taxonomy Switch_7','Healthcare Provider Primary Taxonomy Switch_8',
    'Healthcare Provider Primary Taxonomy Switch_9','Healthcare Provider Primary Taxonomy Switch_9',
    'Healthcare Provider Primary Taxonomy Switch_10','Healthcare Provider Primary Taxonomy Switch_11',
    'Healthcare Provider Primary Taxonomy Switch_12','Healthcare Provider Primary Taxonomy Switch_13',
    'Healthcare Provider Primary Taxonomy Switch_14','Healthcare Provider Primary Taxonomy Switch_15',
    
    
]]

In [142]:
dfmelt_switch = npi_tax_switch.melt(id_vars=['NPI'], var_name='primary_taxonomy_switch')

In [143]:
# Only keep the primary taxonomy
dfmelt_switch = dfmelt_switch[dfmelt_switch['value'] == 'Y']

In [144]:
dfmelt_switch=dfmelt_switch.rename(columns = {'value':'switch_value'})
dfmelt_switch.head()

          NPI                        primary_taxonomy_switch switch_value
0  1679576722  Healthcare Provider Primary Taxonomy Switch_1            Y
2  1497758544  Healthcare Provider Primary Taxonomy Switch_1            Y
3  1306849450  Healthcare Provider Primary Taxonomy Switch_1            Y
5  1023011178  Healthcare Provider Primary Taxonomy Switch_1            Y
6  1932102084  Healthcare Provider Primary Taxonomy Switch_1            Y

In [145]:
npi_tax_code =npidata_raw[[
    'NPI','Healthcare Provider Taxonomy Code_1','Healthcare Provider Taxonomy Code_2',
    'Healthcare Provider Taxonomy Code_3','Healthcare Provider Taxonomy Code_4','Healthcare Provider Taxonomy Code_5',
    'Healthcare Provider Taxonomy Code_6','Healthcare Provider Taxonomy Code_7',
    'Healthcare Provider Taxonomy Code_8','Healthcare Provider Taxonomy Code_9',
    'Healthcare Provider Taxonomy Code_10','Healthcare Provider Taxonomy Code_11',
    'Healthcare Provider Taxonomy Code_12','Healthcare Provider Taxonomy Code_13',
    'Healthcare Provider Taxonomy Code_14','Healthcare Provider Taxonomy Code_15']]

In [146]:
npi_tax_code_melt = npi_tax_code.melt(id_vars=['NPI'], var_name='primary_taxonomy_code')

In [137]:
dfmelt_code=dfmelt_code.rename(columns = {'value':'code_value'})
dfmelt_code.head()

C:\Users\matth\anaconda3\lib\multiprocessing\pool.py:125: DtypeWarning: Columns (27,35,40,46,71,72,73,74,75,78,79,80,81,82,83,84,85,86,151,226,230,231,234,235,238,242,246,250,254,262,266,270,274,278,282,286,290,294,295,297,298,299,302,320,321,322,323) have mixed types.Specify dtype option on import or set low_memory=False.
  result = (True, func(*args, **kwds))
C:\Users\matth\anaconda3\lib\multiprocessing\pool.py:125: DtypeWarning: Columns (27,35,40,80,81,84,85,135,226,227,230,231,234,235,238,242,246,250,254,258,262,266,267,270,321,322,323) have mixed types.Specify dtype option on import or set low_memory=False.
  result = (True, func(*args, **kwds))
C:\Users\matth\anaconda3\lib\multiprocessing\pool.py:125: DtypeWarning: Columns (79,80,81,82,83,84,85,86,147,319,320,321,322,323) have mixed types.Specify dtype option on import or set low_memory=False.
  result = (True, func(*args, **kwds))
C:\Users\matth\anaconda3\lib\multiprocessing\pool.py:125: DtypeWarning: Columns (27,35,40,72,79,80,81,82,83,84,85,86,151,165,226,227,230,231,234,238,242,246,250,254,258,262,266,319,321,322,323) have mixed types.Specify dtype option on import or set low_memory=False.
  result = (True, func(*args, **kwds))
C:\Users\matth\anaconda3\lib\multiprocessing\pool.py:125: DtypeWarning: Columns (27,35,40,46,72,73,79,80,81,82,83,84,85,86,147,151,226,227,230,231,234,235,238,242,246,250,254,255,258,262,266,271,274,278,282,286,320,321,322,323) have mixed types.Specify dtype option on import or set low_memory=False.
  result = (True, func(*args, **kwds))
C:\Users\matth\anaconda3\lib\multiprocessing\pool.py:125: DtypeWarning: Columns (72,80,81,84,85,151,165,226,227,230,231,234,255,319,320,321,322,323) have mixed types.Specify dtype option on import or set low_memory=False.
  result = (True, func(*args, **kwds))
C:\Users\matth\anaconda3\lib\multiprocessing\pool.py:125: DtypeWarning: Columns (27,35,40,46,72,75,78,79,80,81,82,83,84,85,86,151,226,230,234,238,242,246,250,254,258,262,266,267,270,319,320,321,322,323) have mixed types.Specify dtype option on import or set low_memory=False.
  result = (True, func(*args, **kwds))
C:\Users\matth\anaconda3\lib\multiprocessing\pool.py:125: DtypeWarning: Columns (27,35,40,46,72,80,83,84,85,86,151,226,230,320,321,322,323) have mixed types.Specify dtype option on import or set low_memory=False.
  result = (True, func(*args, **kwds))

ValueError: Mismatched dtypes found in `pd.read_csv`/`pd.read_table`.

+--------------------------------------------------------+--------+----------+
| Column                                                 | Found  | Expected |
+--------------------------------------------------------+--------+----------+
| Authorized Official Telephone Number                   | object | float64  |
| Other Provider Identifier Issuer_30                    | object | float64  |
| Other Provider Identifier Issuer_31                    | object | float64  |
| Other Provider Identifier Issuer_32                    | object | float64  |
| Other Provider Identifier Issuer_33                    | object | float64  |
| Other Provider Identifier Issuer_34                    | object | float64  |
| Other Provider Identifier Issuer_35                    | object | float64  |
| Other Provider Identifier Issuer_36                    | object | float64  |
| Other Provider Identifier Issuer_37                    | object | float64  |
| Other Provider Identifier Issuer_39                    | object | float64  |
| Other Provider Identifier Issuer_40                    | object | float64  |
| Other Provider Identifier Issuer_41                    | object | float64  |
| Other Provider Identifier Issuer_42                    | object | float64  |
| Other Provider Identifier Issuer_43                    | object | float64  |
| Other Provider Identifier Issuer_44                    | object | float64  |
| Other Provider Identifier Issuer_45                    | object | float64  |
| Other Provider Identifier Issuer_46                    | object | float64  |
| Other Provider Identifier Issuer_47                    | object | float64  |
| Other Provider Identifier Issuer_48                    | object | float64  |
| Other Provider Identifier Issuer_49                    | object | float64  |
| Other Provider Identifier State_48                     | object | float64  |
| Other Provider Identifier_32                           | object | float64  |
| Other Provider Identifier_33                           | object | float64  |
| Other Provider Identifier_48                           | object | float64  |
| Other Provider Identifier_49                           | object | float64  |
| Provider Business Mailing Address Fax Number           | object | float64  |
| Provider Business Practice Location Address Fax Number | object | float64  |
+--------------------------------------------------------+--------+----------+

The following columns also raised exceptions on conversion:

- Authorized Official Telephone Number
  ValueError("could not convert string to float: '703 752 6197'")
- Other Provider Identifier Issuer_30
  ValueError("could not convert string to float: 'AWARD: WORLD LAUREATE OF U.S.A. FOR PERSONAL ACHIEVEMENTS AND DEDICATION SOCIETY'")
- Other Provider Identifier Issuer_31
  ValueError("could not convert string to float: 'NATIONAL BOARD OF OSTEOPATHIC MEDICAL EXAMINERS-DIPLOMATE STATUS NATIONALLY'")
- Other Provider Identifier Issuer_32
  ValueError("could not convert string to float: 'AMERICAN OSTEOPATHIC BOARD OF FAMILY PHYSICIANS (AOBFP) OSTEOPATHIC MANIPULATION'")
- Other Provider Identifier Issuer_33
  ValueError("could not convert string to float: 'RECOGNITION OF APPRECIATION FOR HEALTH SERVICES: AMERICAN RED CROSS NE TORNADO'")
- Other Provider Identifier Issuer_34
  ValueError("could not convert string to float: 'DOCTORS OF THE WORLD'")
- Other Provider Identifier Issuer_35
  ValueError("could not convert string to float: 'PROFESSIONAL & COMPASSIONATE MEDICAL HEALTH CARE TO OUR AMERICAN VETERANS-US VA'")
- Other Provider Identifier Issuer_36
  ValueError("could not convert string to float: 'AWARD: KEY TO SUCCESS, MEDICAL EXCELLENCE'")
- Other Provider Identifier Issuer_37
  ValueError('could not convert string to float: "DAV DISABLED AMERICAN VETERANS\' COMMANDER\'S CLUB WALL OF HONOR"')
- Other Provider Identifier Issuer_39
  ValueError('could not convert string to float: "DEAN\'S LIST FOR OUTSTANDING ACADEMIC ACHIEVEMENT: KSU KENT STATE UNIVERSITY"')
- Other Provider Identifier Issuer_40
  ValueError("could not convert string to float: 'SOCIETY OF TEACHERS OF FAMILY MEDICINE (STFM)'")
- Other Provider Identifier Issuer_41
  ValueError("could not convert string to float: 'FLIGHT FOR LIFE, STAFF FLIGHT SURGEON-EMERGENCY HELICOPTER RESCUES'")
- Other Provider Identifier Issuer_42
  ValueError('could not convert string to float: "AWARD: LIFE MEMEBER, NATIONAL REGISTRY OF WHO\'S WHO"')
- Other Provider Identifier Issuer_43
  ValueError('could not convert string to float: "CONSUMERS\' RESEARCH COUNSIL OF AMERICA-AMERICA\'S TOP FAMILY PHYSICIANS"')
- Other Provider Identifier Issuer_44
  ValueError("could not convert string to float: 'AMERICAN OSTEOPATHIC BOARD OF FAMILY PHYSICIANS USA BOARD CERTIFICATIONS'")
- Other Provider Identifier Issuer_45
  ValueError("could not convert string to float: 'AMERICAN ACADEMY OF FAMILY PHYSICIANS (AAFP)'")
- Other Provider Identifier Issuer_46
  ValueError("could not convert string to float: 'CERTIFIED PHYSICIAN EXECUTIVE'")
- Other Provider Identifier Issuer_47
  ValueError("could not convert string to float: 'VICE PRESIDENT, CLEVELAND SOCIETY OF CLINICAL HYPNOSIS (C.S.C.H.)'")
- Other Provider Identifier Issuer_48
  ValueError("could not convert string to float: 'STATE OF OHIO MEDICAL LICENSE # 34-006816-R'")
- Other Provider Identifier Issuer_49
  ValueError("could not convert string to float: 'AWARD: KEY OF SUCCESS, PROFESSIONAL PERFORMANCE'")
- Other Provider Identifier State_48
  ValueError("could not convert string to float: 'OH'")
- Other Provider Identifier_32
  ValueError("could not convert string to float: '1598120-01'")
- Other Provider Identifier_33
  ValueError("could not convert string to float: '200061970A'")
- Other Provider Identifier_48
  ValueError("could not convert string to float: '34-006816-R'")
- Other Provider Identifier_49
  ValueError("could not convert string to float: 'ABI'")
- Provider Business Mailing Address Fax Number
  ValueError("could not convert string to float: '82-031-869-4791'")
- Provider Business Practice Location Address Fax Number
  ValueError("could not convert string to float: '011-822-7917-8110'")

Usually this is due to dask's dtype inference failing, and
*may* be fixed by specifying dtypes manually by adding:

dtype={'Authorized Official Telephone Number': 'object',
       'Other Provider Identifier Issuer_30': 'object',
       'Other Provider Identifier Issuer_31': 'object',
       'Other Provider Identifier Issuer_32': 'object',
       'Other Provider Identifier Issuer_33': 'object',
       'Other Provider Identifier Issuer_34': 'object',
       'Other Provider Identifier Issuer_35': 'object',
       'Other Provider Identifier Issuer_36': 'object',
       'Other Provider Identifier Issuer_37': 'object',
       'Other Provider Identifier Issuer_39': 'object',
       'Other Provider Identifier Issuer_40': 'object',
       'Other Provider Identifier Issuer_41': 'object',
       'Other Provider Identifier Issuer_42': 'object',
       'Other Provider Identifier Issuer_43': 'object',
       'Other Provider Identifier Issuer_44': 'object',
       'Other Provider Identifier Issuer_45': 'object',
       'Other Provider Identifier Issuer_46': 'object',
       'Other Provider Identifier Issuer_47': 'object',
       'Other Provider Identifier Issuer_48': 'object',
       'Other Provider Identifier Issuer_49': 'object',
       'Other Provider Identifier State_48': 'object',
       'Other Provider Identifier_32': 'object',
       'Other Provider Identifier_33': 'object',
       'Other Provider Identifier_48': 'object',
       'Other Provider Identifier_49': 'object',
       'Provider Business Mailing Address Fax Number': 'object',
       'Provider Business Practice Location Address Fax Number': 'object'}

to the call to `read_csv`/`read_table`.

In [18]:
dfmelt_code = npi_tax_code.melt(id_vars=['NPI'], var_name='primary_taxonomy_code')

In [22]:
dfmelt_code = dfmelt_code.merge(dfmelt_switch, how='inner', on='NPI')

In [21]:
npidata = npidata.merge(
    dfmelt_code,
    how='left',
    on='NPI'
)

In [22]:
dfmelt_code.head(5)

C:\Users\matth\anaconda3\lib\multiprocessing\pool.py:125: DtypeWarning: Columns (79,80,81,82,83,84,85,86,147,319,320,321,322,323) have mixed types.Specify dtype option on import or set low_memory=False.
  result = (True, func(*args, **kwds))
C:\Users\matth\anaconda3\lib\multiprocessing\pool.py:125: DtypeWarning: Columns (27,35,40,72,79,80,81,82,83,84,85,86,151,165,226,227,230,231,234,238,242,246,250,254,258,262,266,319,321,322,323) have mixed types.Specify dtype option on import or set low_memory=False.
  result = (True, func(*args, **kwds))
C:\Users\matth\anaconda3\lib\multiprocessing\pool.py:125: DtypeWarning: Columns (27,35,40,46,71,72,73,74,75,78,79,80,81,82,83,84,85,86,151,226,230,231,234,235,238,242,246,250,254,262,266,270,274,278,282,286,290,294,295,297,298,299,302,320,321,322,323) have mixed types.Specify dtype option on import or set low_memory=False.
  result = (True, func(*args, **kwds))
C:\Users\matth\anaconda3\lib\multiprocessing\pool.py:125: DtypeWarning: Columns (72,80,81,84,85,151,165,226,227,230,231,234,255,319,320,321,322,323) have mixed types.Specify dtype option on import or set low_memory=False.
  result = (True, func(*args, **kwds))
C:\Users\matth\anaconda3\lib\multiprocessing\pool.py:125: DtypeWarning: Columns (27,35,40,46,72,73,79,80,81,82,83,84,85,86,147,151,226,227,230,231,234,235,238,242,246,250,254,255,258,262,266,271,274,278,282,286,320,321,322,323) have mixed types.Specify dtype option on import or set low_memory=False.
  result = (True, func(*args, **kwds))
C:\Users\matth\anaconda3\lib\multiprocessing\pool.py:125: DtypeWarning: Columns (27,35,40,46,72,75,78,79,80,81,82,83,84,85,86,151,226,230,234,238,242,246,250,254,258,262,266,267,270,319,320,321,322,323) have mixed types.Specify dtype option on import or set low_memory=False.
  result = (True, func(*args, **kwds))
C:\Users\matth\anaconda3\lib\multiprocessing\pool.py:125: DtypeWarning: Columns (27,35,40,80,81,84,85,135,226,227,230,231,234,235,238,242,246,250,254,258,262,266,267,270,321,322,323) have mixed types.Specify dtype option on import or set low_memory=False.
  result = (True, func(*args, **kwds))

ValueError: Mismatched dtypes found in `pd.read_csv`/`pd.read_table`.

+--------------------------------------------------------+--------+----------+
| Column                                                 | Found  | Expected |
+--------------------------------------------------------+--------+----------+
| Other Provider Identifier Issuer_30                    | object | float64  |
| Other Provider Identifier Issuer_31                    | object | float64  |
| Other Provider Identifier Issuer_32                    | object | float64  |
| Other Provider Identifier Issuer_33                    | object | float64  |
| Other Provider Identifier Issuer_34                    | object | float64  |
| Other Provider Identifier Issuer_35                    | object | float64  |
| Other Provider Identifier Issuer_36                    | object | float64  |
| Other Provider Identifier Issuer_37                    | object | float64  |
| Other Provider Identifier Issuer_38                    | object | float64  |
| Other Provider Identifier Issuer_39                    | object | float64  |
| Other Provider Identifier Issuer_40                    | object | float64  |
| Other Provider Identifier_31                           | object | float64  |
| Other Provider Identifier_32                           | object | float64  |
| Provider Business Mailing Address Fax Number           | object | float64  |
| Provider Business Practice Location Address Fax Number | object | float64  |
+--------------------------------------------------------+--------+----------+

The following columns also raised exceptions on conversion:

- Other Provider Identifier Issuer_30
  ValueError("could not convert string to float: 'LICENSE'")
- Other Provider Identifier Issuer_31
  ValueError("could not convert string to float: 'ADVANTICA EYECARE'")
- Other Provider Identifier Issuer_32
  ValueError("could not convert string to float: 'AMERICAN REPUBLIC'")
- Other Provider Identifier Issuer_33
  ValueError("could not convert string to float: 'PIRELLI ARMSTRONG'")
- Other Provider Identifier Issuer_34
  ValueError("could not convert string to float: 'AMERICARE'")
- Other Provider Identifier Issuer_35
  ValueError("could not convert string to float: 'MIDLANDS CHOICE'")
- Other Provider Identifier Issuer_36
  ValueError("could not convert string to float: 'ACCOUNTABLE HEALTH'")
- Other Provider Identifier Issuer_37
  ValueError("could not convert string to float: 'WELLMARK BLUE SHIELD'")
- Other Provider Identifier Issuer_38
  ValueError("could not convert string to float: 'GLACERS LOCAL #558'")
- Other Provider Identifier Issuer_39
  ValueError("could not convert string to float: 'UNITED AMERICAN INSURANCE COMPANY'")
- Other Provider Identifier Issuer_40
  ValueError("could not convert string to float: 'COVENTRY ADVANTRA'")
- Other Provider Identifier_31
  ValueError("could not convert string to float: 'XHSP42759'")
- Other Provider Identifier_32
  ValueError("could not convert string to float: 'OEG001239'")
- Provider Business Mailing Address Fax Number
  ValueError("could not convert string to float: '000226-8802'")
- Provider Business Practice Location Address Fax Number
  ValueError("could not convert string to float: '000226-8802'")

Usually this is due to dask's dtype inference failing, and
*may* be fixed by specifying dtypes manually by adding:

dtype={'Other Provider Identifier Issuer_30': 'object',
       'Other Provider Identifier Issuer_31': 'object',
       'Other Provider Identifier Issuer_32': 'object',
       'Other Provider Identifier Issuer_33': 'object',
       'Other Provider Identifier Issuer_34': 'object',
       'Other Provider Identifier Issuer_35': 'object',
       'Other Provider Identifier Issuer_36': 'object',
       'Other Provider Identifier Issuer_37': 'object',
       'Other Provider Identifier Issuer_38': 'object',
       'Other Provider Identifier Issuer_39': 'object',
       'Other Provider Identifier Issuer_40': 'object',
       'Other Provider Identifier_31': 'object',
       'Other Provider Identifier_32': 'object',
       'Provider Business Mailing Address Fax Number': 'object',
       'Provider Business Practice Location Address Fax Number': 'object'}

to the call to `read_csv`/`read_table`.

C:\Users\matth\anaconda3\lib\multiprocessing\pool.py:125: DtypeWarning: Columns (27,35,40,46,72,80,83,84,85,86,151,226,230,320,321,322,323) have mixed types.Specify dtype option on import or set low_memory=False.
  result = (True, func(*args, **kwds))

In [38]:
# Pivot from widet to long format
npi_taxonomy = pd.wide_to_long(
    npi_taxonomy,
    stubnames=['Healthcare Provider Taxonomy Code', 'Healthcare Provider Primary Taxonomy Switch'],
    i=['NPI'], 
    j='primary_taxonomy_index',
    sep="_"
)

# Only keep the primary taxonomy
npi_taxonomy = npi_taxonomy[npi_taxonomy['Healthcare Provider Primary Taxonomy Switch'] == 'Y']

# Housekeeping
npi_taxonomy = npi_taxonomy.reset_index()\
    .drop(columns=['primary_taxonomy_index', 'Healthcare Provider Primary Taxonomy Switch'])\
    .rename({ 'Healthcare Provider Taxonomy Code': 'primary_taxonomy' }, axis=1)

npi_taxonomy

AttributeError: 'DataFrame' object has no attribute 'duplicated'

In [5]:
# Only keep the primary taxonomy
npi_taxonomy = npi_taxonomy[npi_taxonomy['Healthcare Provider Primary Taxonomy Switch'] == 'Y']

KeyError: 'Healthcare Provider Primary Taxonomy Switch'

In [10]:
npi_taxonomy.melt(id_vars=['NPI'], var_name='primary_taxonomy_index')

Dask DataFrame Structure:
                   NPI primary_taxonomy_index   value
npartitions=126
                 int64                 object  object
                   ...                    ...     ...
...                ...                    ...     ...
                   ...                    ...     ...
                   ...                    ...     ...
Dask Name: melt, 378 tasks

In [35]:
npidata = pd.concat([
    npidata_raw[['NPI']],
    # Entity Type Code: 1 = Provider (doctors, nurses, etc.) / 2 = Facility (Hospitals, Urgent Care, Doctors Offices) 
    npidata_raw[['Entity Type Code']],
    # Entity Name: Either First/Last or Organization or Other Organization Name contained in the following fields:
    npidata_raw.loc[:, 'Provider Organization Name (Legal Business Name)':'Provider Credential Text'],
    # Address: Business Practice Location (not mailing), contained in the following fields:
    npidata_raw.loc[:, 'Provider First Line Business Mailing Address':'Provider Business Mailing Address Postal Code'],
], axis=1)

npidata.head()

TypeError: cannot concatenate object of type '<class 'dask.dataframe.core.DataFrame'>'; only Series and DataFrame objs are valid

In [28]:
npidata_raw.shape

(Delayed('int-8b465115-6b6d-4e1c-9ce5-dfeb3c5fa6c5'), 330)

In [2]:
#hop_chunks = pd.read_csv('data/DocGraph_Hop_Teaming_2017.csv',chunksize = 1000000) # nrows = 10000
# hop_chunks = dd.read_csv('data/DocGraph_Hop_Teaming_2017.csv')

In [4]:
#hop_chunks.head(10)

,from_npi,to_npi,patient_count,transaction_count,average_day_wait,std_day_wait
0,1003863580,1000000004,19,19,108.895,84.598
1,1043250400,1000000004,20,20,87.000,77.173
2,1033239413,1000000004,20,20,58.800,76.982
3,1033142146,1000000004,491,535,10.232,36.558
4,1013957562,1000000004,25,26,78.692,59.305
5,1013952357,1000000004,20,20,21.100,66.988
6,1013977990,1003000126,134,145,27.352,51.137
7,1023008182,1003000126,13,14,21.643,58.885
8,1013996669,1003000126,91,92,35.152,68.009
9,1033138250,1003000126,47,49,91.939,76.125

In [ ]:
# hop_df = pd.concat(hop_chunks)

In [12]:
#npidata_raw = pd.read_csv('data/npidata_pfile_20050523-20210207.csv',chunksize =1000000)

In [14]:
npidata_raw.head()

AttributeError: 'TextFileReader' object has no attribute 'head'

In [17]:
hop_chunks.shape

(203330907, 6)

In [18]:
hop_chunks.head(10)

,from_npi,to_npi,patient_count,transaction_count,average_day_wait,std_day_wait
0,1003863580,1000000004,19,19,108.895,84.598
1,1043250400,1000000004,20,20,87.000,77.173
2,1033239413,1000000004,20,20,58.800,76.982
3,1033142146,1000000004,491,535,10.232,36.558
4,1013957562,1000000004,25,26,78.692,59.305
5,1013952357,1000000004,20,20,21.100,66.988
6,1013977990,1003000126,134,145,27.352,51.137
7,1023008182,1003000126,13,14,21.643,58.885
8,1013996669,1003000126,91,92,35.152,68.009
9,1033138250,1003000126,47,49,91.939,76.125

In [11]:
npi_taxonomy = pd.concat([
    npidata_raw[['NPI']],
    # The provider's taxonomy code, which is contained in one of the 'Healthcare Provider Taxonomy Code*' columns
    npidata_raw[npidata_raw.columns[pd.Series(npidata_raw.columns).str.startswith('Healthcare Provider Taxonomy Code_')]],
    npidata_raw[npidata_raw.columns[pd.Series(npidata_raw.columns).str.startswith('Healthcare Provider Primary Taxonomy Switch_')]]
], axis=1)

npi_taxonomy.head()

TypeError: cannot concatenate object of type '<class 'dask.dataframe.core.DataFrame'>'; only Series and DataFrame objs are valid

In [ ]:
'''c_nppes_chunks = nppes_chunks[['NPI','Entity Type Code','Provider Organization Name (Legal Business Name)',
                               'Provider Last Name (Legal Name)','Provider First Name',
                                'Provider Middle Name','Provider Name Prefix Text','Provider Name Suffix Text',
                                'Provider Credential Text','Provider First Line Business Mailing Address',
                'Provider Second Line Business Mailing Address','Provider Business Mailing Address City Name',
                'Provider Business Mailing Address State Name','Provider Business Mailing Address Postal Code',
                'Healthcare Provider Primary Taxonomy Switch_1','Healthcare Provider Primary Taxonomy Switch_2',
                'Healthcare Provider Primary Taxonomy Switch_3','Healthcare Provider Primary Taxonomy Switch_4',
                'Healthcare Provider Primary Taxonomy Switch_5','Healthcare Provider Primary Taxonomy Switch_6'
                ]]'''

In [4]:
nppes_chunks.columns.tolist()

['NPI',
 'Entity Type Code',
 'Replacement NPI',
 'Employer Identification Number (EIN)',
 'Provider Organization Name (Legal Business Name)',
 'Provider Last Name (Legal Name)',
 'Provider First Name',
 'Provider Middle Name',
 'Provider Name Prefix Text',
 'Provider Name Suffix Text',
 'Provider Credential Text',
 'Provider Other Organization Name',
 'Provider Other Organization Name Type Code',
 'Provider Other Last Name',
 'Provider Other First Name',
 'Provider Other Middle Name',
 'Provider Other Name Prefix Text',
 'Provider Other Name Suffix Text',
 'Provider Other Credential Text',
 'Provider Other Last Name Type Code',
 'Provider First Line Business Mailing Address',
 'Provider Second Line Business Mailing Address',
 'Provider Business Mailing Address City Name',
 'Provider Business Mailing Address State Name',
 'Provider Business Mailing Address Postal Code',
 'Provider Business Mailing Address Country Code (If outside U.S.)',
 'Provider Business Mailing Address Telephone Number',
 'Provider Business Mailing Address Fax Number',
 'Provider First Line Business Practice Location Address',
 'Provider Second Line Business Practice Location Address',
 'Provider Business Practice Location Address City Name',
 'Provider Business Practice Location Address State Name',
 'Provider Business Practice Location Address Postal Code',
 'Provider Business Practice Location Address Country Code (If outside U.S.)',
 'Provider Business Practice Location Address Telephone Number',
 'Provider Business Practice Location Address Fax Number',
 'Provider Enumeration Date',
 'Last Update Date',
 'NPI Deactivation Reason Code',
 'NPI Deactivation Date',
 'NPI Reactivation Date',
 'Provider Gender Code',
 'Authorized Official Last Name',
 'Authorized Official First Name',
 'Authorized Official Middle Name',
 'Authorized Official Title or Position',
 'Authorized Official Telephone Number',
 'Healthcare Provider Taxonomy Code_1',
 'Provider License Number_1',
 'Provider License Number State Code_1',
 'Healthcare Provider Primary Taxonomy Switch_1',
 'Healthcare Provider Taxonomy Code_2',
 'Provider License Number_2',
 'Provider License Number State Code_2',
 'Healthcare Provider Primary Taxonomy Switch_2',
 'Healthcare Provider Taxonomy Code_3',
 'Provider License Number_3',
 'Provider License Number State Code_3',
 'Healthcare Provider Primary Taxonomy Switch_3',
 'Healthcare Provider Taxonomy Code_4',
 'Provider License Number_4',
 'Provider License Number State Code_4',
 'Healthcare Provider Primary Taxonomy Switch_4',
 'Healthcare Provider Taxonomy Code_5',
 'Provider License Number_5',
 'Provider License Number State Code_5',
 'Healthcare Provider Primary Taxonomy Switch_5',
 'Healthcare Provider Taxonomy Code_6',
 'Provider License Number_6',
 'Provider License Number State Code_6',
 'Healthcare Provider Primary Taxonomy Switch_6',
 'Healthcare Provider Taxonomy Code_7',
 'Provider License Number_7',
 'Provider License Number State Code_7',
 'Healthcare Provider Primary Taxonomy Switch_7',
 'Healthcare Provider Taxonomy Code_8',
 'Provider License Number_8',
 'Provider License Number State Code_8',
 'Healthcare Provider Primary Taxonomy Switch_8',
 'Healthcare Provider Taxonomy Code_9',
 'Provider License Number_9',
 'Provider License Number State Code_9',
 'Healthcare Provider Primary Taxonomy Switch_9',
 'Healthcare Provider Taxonomy Code_10',
 'Provider License Number_10',
 'Provider License Number State Code_10',
 'Healthcare Provider Primary Taxonomy Switch_10',
 'Healthcare Provider Taxonomy Code_11',
 'Provider License Number_11',
 'Provider License Number State Code_11',
 'Healthcare Provider Primary Taxonomy Switch_11',
 'Healthcare Provider Taxonomy Code_12',
 'Provider License Number_12',
 'Provider License Number State Code_12',
 'Healthcare Provider Primary Taxonomy Switch_12',
 'Healthcare Provider Taxonomy Code_13',
 'Provider License Number_13',
 'Provider License Number State Code_13',
 'Healthcare Provider Primary Taxonomy Switch_13',
 'Healthcare Provider Taxonomy Code_14',
 'Provider License Number_14',
 'Provider License Number State Code_14',
 'Healthcare Provider Primary Taxonomy Switch_14',
 'Healthcare Provider Taxonomy Code_15',
 'Provider License Number_15',
 'Provider License Number State Code_15',
 'Healthcare Provider Primary Taxonomy Switch_15',
 'Other Provider Identifier_1',
 'Other Provider Identifier Type Code_1',
 'Other Provider Identifier State_1',
 'Other Provider Identifier Issuer_1',
 'Other Provider Identifier_2',
 'Other Provider Identifier Type Code_2',
 'Other Provider Identifier State_2',
 'Other Provider Identifier Issuer_2',
 'Other Provider Identifier_3',
 'Other Provider Identifier Type Code_3',
 'Other Provider Identifier State_3',
 'Other Provider Identifier Issuer_3',
 'Other Provider Identifier_4',
 'Other Provider Identifier Type Code_4',
 'Other Provider Identifier State_4',
 'Other Provider Identifier Issuer_4',
 'Other Provider Identifier_5',
 'Other Provider Identifier Type Code_5',
 'Other Provider Identifier State_5',
 'Other Provider Identifier Issuer_5',
 'Other Provider Identifier_6',
 'Other Provider Identifier Type Code_6',
 'Other Provider Identifier State_6',
 'Other Provider Identifier Issuer_6',
 'Other Provider Identifier_7',
 'Other Provider Identifier Type Code_7',
 'Other Provider Identifier State_7',
 'Other Provider Identifier Issuer_7',
 'Other Provider Identifier_8',
 'Other Provider Identifier Type Code_8',
 'Other Provider Identifier State_8',
 'Other Provider Identifier Issuer_8',
 'Other Provider Identifier_9',
 'Other Provider Identifier Type Code_9',
 'Other Provider Identifier State_9',
 'Other Provider Identifier Issuer_9',
 'Other Provider Identifier_10',
 'Other Provider Identifier Type Code_10',
 'Other Provider Identifier State_10',
 'Other Provider Identifier Issuer_10',
 'Other Provider Identifier_11',
 'Other Provider Identifier Type Code_11',
 'Other Provider Identifier State_11',
 'Other Provider Identifier Issuer_11',
 'Other Provider Identifier_12',
 'Other Provider Identifier Type Code_12',
 'Other Provider Identifier State_12',
 'Other Provider Identifier Issuer_12',
 'Other Provider Identifier_13',
 'Other Provider Identifier Type Code_13',
 'Other Provider Identifier State_13',
 'Other Provider Identifier Issuer_13',
 'Other Provider Identifier_14',
 'Other Provider Identifier Type Code_14',
 'Other Provider Identifier State_14',
 'Other Provider Identifier Issuer_14',
 'Other Provider Identifier_15',
 'Other Provider Identifier Type Code_15',
 'Other Provider Identifier State_15',
 'Other Provider Identifier Issuer_15',
 'Other Provider Identifier_16',
 'Other Provider Identifier Type Code_16',
 'Other Provider Identifier State_16',
 'Other Provider Identifier Issuer_16',
 'Other Provider Identifier_17',
 'Other Provider Identifier Type Code_17',
 'Other Provider Identifier State_17',
 'Other Provider Identifier Issuer_17',
 'Other Provider Identifier_18',
 'Other Provider Identifier Type Code_18',
 'Other Provider Identifier State_18',
 'Other Provider Identifier Issuer_18',
 'Other Provider Identifier_19',
 'Other Provider Identifier Type Code_19',
 'Other Provider Identifier State_19',
 'Other Provider Identifier Issuer_19',
 'Other Provider Identifier_20',
 'Other Provider Identifier Type Code_20',
 'Other Provider Identifier State_20',
 'Other Provider Identifier Issuer_20',
 'Other Provider Identifier_21',
 'Other Provider Identifier Type Code_21',
 'Other Provider Identifier State_21',
 'Other Provider Identifier Issuer_21',
 'Other Provider Identifier_22',
 'Other Provider Identifier Type Code_22',
 'Other Provider Identifier State_22',
 'Other Provider Identifier Issuer_22',
 'Other Provider Identifier_23',
 'Other Provider Identifier Type Code_23',
 'Other Provider Identifier State_23',
 'Other Provider Identifier Issuer_23',
 'Other Provider Identifier_24',
 'Other Provider Identifier Type Code_24',
 'Other Provider Identifier State_24',
 'Other Provider Identifier Issuer_24',
 'Other Provider Identifier_25',
 'Other Provider Identifier Type Code_25',
 'Other Provider Identifier State_25',
 'Other Provider Identifier Issuer_25',
 'Other Provider Identifier_26',
 'Other Provider Identifier Type Code_26',
 'Other Provider Identifier State_26',
 'Other Provider Identifier Issuer_26',
 'Other Provider Identifier_27',
 'Other Provider Identifier Type Code_27',
 'Other Provider Identifier State_27',
 'Other Provider Identifier Issuer_27',
 'Other Provider Identifier_28',
 'Other Provider Identifier Type Code_28',
 'Other Provider Identifier State_28',
 'Other Provider Identifier Issuer_28',
 'Other Provider Identifier_29',
 'Other Provider Identifier Type Code_29',
 'Other Provider Identifier State_29',
 'Other Provider Identifier Issuer_29',
 'Other Provider Identifier_30',
 'Other Provider Identifier Type Code_30',
 'Other Provider Identifier State_30',
 'Other Provider Identifier Issuer_30',
 'Other Provider Identifier_31',
 'Other Provider Identifier Type Code_31',
 'Other Provider Identifier State_31',
 'Other Provider Identifier Issuer_31',
 'Other Provider Identifier_32',
 'Other Provider Identifier Type Code_32',
 'Other Provider Identifier State_32',
 'Other Provider Identifier Issuer_32',
 'Other Provider Identifier_33',
 'Other Provider Identifier Type Code_33',
 'Other Provider Identifier State_33',
 'Other Provider Identifier Issuer_33',
 'Other Provider Identifier_34',
 'Other Provider Identifier Type Code_34',
 'Other Provider Identifier State_34',
 'Other Provider Identifier Issuer_34',
 'Other Provider Identifier_35',
 'Other Provider Identifier Type Code_35',
 'Other Provider Identifier State_35',
 'Other Provider Identifier Issuer_35',
 'Other Provider Identifier_36',
 'Other Provider Identifier Type Code_36',
 'Other Provider Identifier State_36',
 'Other Provider Identifier Issuer_36',
 'Other Provider Identifier_37',
 'Other Provider Identifier Type Code_37',
 'Other Provider Identifier State_37',
 'Other Provider Identifier Issuer_37',
 'Other Provider Identifier_38',
 'Other Provider Identifier Type Code_38',
 'Other Provider Identifier State_38',
 'Other Provider Identifier Issuer_38',
 'Other Provider Identifier_39',
 'Other Provider Identifier Type Code_39',
 'Other Provider Identifier State_39',
 'Other Provider Identifier Issuer_39',
 'Other Provider Identifier_40',
 'Other Provider Identifier Type Code_40',
 'Other Provider Identifier State_40',
 'Other Provider Identifier Issuer_40',
 'Other Provider Identifier_41',
 'Other Provider Identifier Type Code_41',
 'Other Provider Identifier State_41',
 'Other Provider Identifier Issuer_41',
 'Other Provider Identifier_42',
 'Other Provider Identifier Type Code_42',
 'Other Provider Identifier State_42',
 'Other Provider Identifier Issuer_42',
 'Other Provider Identifier_43',
 'Other Provider Identifier Type Code_43',
 'Other Provider Identifier State_43',
 'Other Provider Identifier Issuer_43',
 'Other Provider Identifier_44',
 'Other Provider Identifier Type Code_44',
 'Other Provider Identifier State_44',
 'Other Provider Identifier Issuer_44',
 'Other Provider Identifier_45',
 'Other Provider Identifier Type Code_45',
 'Other Provider Identifier State_45',
 'Other Provider Identifier Issuer_45',
 'Other Provider Identifier_46',
 'Other Provider Identifier Type Code_46',
 'Other Provider Identifier State_46',
 'Other Provider Identifier Issuer_46',
 'Other Provider Identifier_47',
 'Other Provider Identifier Type Code_47',
 'Other Provider Identifier State_47',
 'Other Provider Identifier Issuer_47',
 'Other Provider Identifier_48',
 'Other Provider Identifier Type Code_48',
 'Other Provider Identifier State_48',
 'Other Provider Identifier Issuer_48',
 'Other Provider Identifier_49',
 'Other Provider Identifier Type Code_49',
 'Other Provider Identifier State_49',
 'Other Provider Identifier Issuer_49',
 'Other Provider Identifier_50',
 'Other Provider Identifier Type Code_50',
 'Other Provider Identifier State_50',
 'Other Provider Identifier Issuer_50',
 'Is Sole Proprietor',
 'Is Organization Subpart',
 'Parent Organization LBN',
 'Parent Organization TIN',
 'Authorized Official Name Prefix Text',
 'Authorized Official Name Suffix Text',
 'Authorized Official Credential Text',
 'Healthcare Provider Taxonomy Group_1',
 'Healthcare Provider Taxonomy Group_2',
 'Healthcare Provider Taxonomy Group_3',
 'Healthcare Provider Taxonomy Group_4',
 'Healthcare Provider Taxonomy Group_5',
 'Healthcare Provider Taxonomy Group_6',
 'Healthcare Provider Taxonomy Group_7',
 'Healthcare Provider Taxonomy Group_8',
 'Healthcare Provider Taxonomy Group_9',
 'Healthcare Provider Taxonomy Group_10',
 'Healthcare Provider Taxonomy Group_11',
 'Healthcare Provider Taxonomy Group_12',
 'Healthcare Provider Taxonomy Group_13',
 'Healthcare Provider Taxonomy Group_14',
 'Healthcare Provider Taxonomy Group_15',
 'Certification Date']

In [12]:
nppes_chunks['Healthcare Provider Taxonomy Code_1'].head(10)

0    207X00000X
1    207RC0000X
2    251G00000X
3    2085R0202X
4    174400000X
5    251G00000X
6    207RC0000X
7    231H00000X
8    207R00000X
9    208000000X
Name: Healthcare Provider Taxonomy Code_1, dtype: object

In [15]:
nppes_chunks['Healthcare Provider Primary Taxonomy Switch_1'].head(10)

0    Y
1    N
2    Y
3    Y
4    N
5    Y
6    Y
7    Y
8    Y
9    Y
Name: Healthcare Provider Primary Taxonomy Switch_1, dtype: object

# Relavent columns
* NPI
* Entity Type
* Entity Name
* Address
* Taxonomy Code

In [8]:
nppes_chunks.shape

(10000, 330)

In [9]:
nppes_chunks.head()

,NPI,Entity Type Code,Replacement NPI,Employer Identification Number (EIN),Provider Organization Name (Legal Business Name),Provider Last Name (Legal Name),Provider First Name,Provider Middle Name,Provider Name Prefix Text,Provider Name Suffix Text,...,Healthcare Provider Taxonomy Group_7,Healthcare Provider Taxonomy Group_8,Healthcare Provider Taxonomy Group_9,Healthcare Provider Taxonomy Group_10,Healthcare Provider Taxonomy Group_11,Healthcare Provider Taxonomy Group_12,Healthcare Provider Taxonomy Group_13,Healthcare Provider Taxonomy Group_14,Healthcare Provider Taxonomy Group_15,Certification Date
0,1679576722,1.0,NaN,NaN,NaN,WIEBE,DAVID,A,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1588667638,1.0,NaN,NaN,NaN,PILCHER,WILLIAM,C,DR.,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1497758544,2.0,NaN,<UNAVAIL>,"CUMBERLAND COUNTY HOSPITAL SYSTEM, INC",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1306849450,1.0,NaN,NaN,NaN,SMITSON,HAROLD,LEROY,DR.,II,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1215930367,1.0,NaN,NaN,NaN,GRESSOT,LAURENT,NaN,DR.,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN